#version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: docker/django/Dockerfile
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
      - ./backend/media:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: "no"
    #stop_grace_period: 30s

  frontend:
    image: node:20-alpine
    working_dir: /frontend
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    volumes:
      - ./frontend:/frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_BASE_URL: http://localhost:8000/api/v1
    depends_on:
      backend:
        condition: service_started
    restart: "no"
    stop_grace_period: 15s


  db:
    image: postgres:15
    container_name: lending_db
    ports:
      - "5433:5432"
    #restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      HOST: ${DB_HOST}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d lending_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: "no"
    stop_grace_period: 30s

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: "no"
    stop_grace_period: 15s

  worker:
    build:
      context: ./backend
      dockerfile: docker/django/Dockerfile
    command: celery -A config worker -l info
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: "no"
  
     

  beat:
    build:
      context: ./backend
      dockerfile: docker/django/Dockerfile
    command: celery -A config beat -l info
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: "no"
  

volumes:
  postgres_data:
  static_volume:
