<<<<<<< HEAD
# Generated by Django 4.2.29 on 2026-03-25 13:10
=======
# Generated by Django 4.2.29 on 2026-03-25 15:43
>>>>>>> rupert_users

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('score', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
=======
                ('score', models.IntegerField(default=0)),
                ('category', models.CharField(blank=True, max_length=50)),
>>>>>>> rupert_users
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
