# Generated by Django 5.2.12 on 2026-04-02 11:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bank_name', models.CharField(max_length=120)),
                ('account_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('customer_category', models.CharField(choices=[('military', 'Military'), ('paramilitary', 'Paramilitary'), ('civil_servant', 'Civil Servant'), ('private_sector', 'Private Sector'), ('businessman', 'Businessman')], max_length=30)),
                ('residency_status', models.CharField(choices=[('resident_nigeria', 'Resident Nigeria'), ('diaspora', 'Diaspora')], max_length=30)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('national_id', models.CharField(blank=True, max_length=50, null=True)),
                ('bvn', models.CharField(blank=True, max_length=20, null=True)),
                ('nin', models.CharField(blank=True, max_length=20, null=True)),
                ('country_of_residence', models.CharField(default='Nigeria', max_length=100)),
                ('state_of_residence', models.CharField(blank=True, max_length=100, null=True)),
                ('foreign_address', models.TextField(blank=True, null=True)),
                ('has_nigerian_bank_account', models.BooleanField(default=True)),
                ('has_foreign_bank_account', models.BooleanField(default=False)),
                ('currency_preference', models.CharField(choices=[('NGN', 'Naira'), ('USD', 'US Dollar'), ('GBP', 'Pound'), ('EUR', 'Euro')], default='NGN', max_length=10)),
                ('employer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('staff_or_service_number', models.CharField(blank=True, max_length=100, null=True)),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('average_monthly_turnover', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('years_in_business', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
