# Generated by Django 5.2.12 on 2026-04-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bank_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bvn_verification_status',
            field=models.CharField(choices=[('not_verified', 'Not Verified'), ('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], default='not_verified', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='nin_verification_status',
            field=models.CharField(choices=[('not_verified', 'Not Verified'), ('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], default='not_verified', max_length=20),
        ),
    ]
