# Generated by Django 5.2.12 on 2026-04-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_profile_account_number_profile_bank_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='bank_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='is_salary_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='verification_reference',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
