FROM python:3.12-slim
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /app
RUN apt-get update && apt-get install -y build-essential libpq-dev netcat-openbsd && rm -rf /var/lib/apt/lists/*
COPY requirements/ /app/requirements/
RUN pip install --no-cache-dir -r /app/requirements/production.txt
COPY . /app/
RUN chmod +x /app/docker/django/entrypoint.sh
