# Generated by Django 5.2.12 on 2026-03-31 16:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('debt_to_income_ratio', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('max_loan_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('decision', models.CharField(choices=[('eligible', 'Eligible'), ('not_eligible', 'Not Eligible'), ('review', 'Manual Review')], max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
